"""
Состояния для обработчиков публикации
"""

# Базовые состояния (общие для всех типов)
CHOOSE_ACCOUNT = 'PUBLISH_CHOOSE_ACCOUNT'
UPLOAD_MEDIA = 'PUBLISH_UPLOAD_MEDIA' 
ENTER_CAPTION = 'PUBLISH_ENTER_CAPTION'
ENTER_HASHTAGS = 'PUBLISH_ENTER_HASHTAGS'
CONFIRM_PUBLISH = 'PUBLISH_CONFIRM'
CHOOSE_SCHEDULE = 'PUBLISH_CHOOSE_SCHEDULE'
CHOOSE_HIDE_FROM_FEED = 'PUBLISH_HIDE_FROM_FEED'

# Состояния для постов
class PostStates:
    # Выбор аккаунтов
    CHOOSE_ACCOUNT = 'POST_CHOOSE_ACCOUNT'
    SOURCE_SELECTION = 'POST_SOURCE_SELECTION'
    FOLDER_SELECTION = 'POST_FOLDER_SELECTION'
    ACCOUNTS_LIST = 'POST_ACCOUNTS_LIST'
    CONFIRM_SELECTION = 'POST_CONFIRM_SELECTION'
    
    # Медиа
    MEDIA_UPLOAD = 'POST_MEDIA_UPLOAD'
    MEDIA_ACTIONS = 'POST_MEDIA_ACTIONS'
    
    # Контент
    ENTER_CAPTION = 'POST_ENTER_CAPTION'
    CAPTION_INPUT = 'POST_CAPTION_INPUT'
    CAPTION_ACTIONS = 'POST_CAPTION_ACTIONS'
    ENTER_HASHTAGS = 'POST_ENTER_HASHTAGS'
    HASHTAGS_INPUT = 'POST_HASHTAGS_INPUT'
    HASHTAGS_ACTIONS = 'POST_HASHTAGS_ACTIONS'
    
    # Подтверждение
    CONFIRM_PUBLISH = 'POST_CONFIRM_PUBLISH'
    FINAL_CONFIRMATION = 'POST_FINAL_CONFIRMATION'
    SCHEDULE_TIME = 'POST_SCHEDULE_TIME'

# Состояния для Stories
class StoryStates:
    # Выбор аккаунтов
    CHOOSE_ACCOUNT = 'STORY_CHOOSE_ACCOUNT'
    SOURCE_SELECTION = 'STORY_SOURCE_SELECTION'
    FOLDER_SELECTION = 'STORY_FOLDER_SELECTION'
    ACCOUNTS_LIST = 'STORY_ACCOUNTS_LIST'
    CONFIRM_SELECTION = 'STORY_CONFIRM_SELECTION'
    
    # Медиа
    MEDIA_UPLOAD = 'STORY_MEDIA_UPLOAD'
    
    # Контент
    ENTER_CAPTION = 'STORY_ENTER_CAPTION'
    CAPTION_INPUT = 'STORY_CAPTION_INPUT'
    CAPTION_ACTIONS = 'STORY_CAPTION_ACTIONS'
    
    # Функции
    ADD_FEATURES = 'STORY_ADD_FEATURES'
    ADD_MENTIONS = 'STORY_ADD_MENTIONS'
    ADD_LINK = 'STORY_ADD_LINK'
    ADD_LOCATION = 'STORY_ADD_LOCATION'
    ADD_HASHTAGS = 'STORY_ADD_HASHTAGS'
    ADD_TEXT = 'STORY_ADD_TEXT'
    
    # Подтверждение
    CONFIRM_PUBLISH = 'STORY_CONFIRM_PUBLISH'
    SCHEDULE_TIME = 'STORY_SCHEDULE_TIME'

# Состояния для Reels  
class ReelsStates:
    # Выбор аккаунтов
    CHOOSE_ACCOUNT = 'REELS_CHOOSE_ACCOUNT'
    SOURCE_SELECTION = 'REELS_SOURCE_SELECTION'
    FOLDER_SELECTION = 'REELS_FOLDER_SELECTION'
    ACCOUNTS_LIST = 'REELS_ACCOUNTS_LIST'
    CONFIRM_SELECTION = 'REELS_CONFIRM_SELECTION'
    
    # Медиа
    MEDIA_UPLOAD = 'REELS_MEDIA_UPLOAD'
    UPLOAD_MEDIA = 'REELS_UPLOAD_MEDIA'
    
    # Контент
    ENTER_CAPTION = 'REELS_ENTER_CAPTION'
    CAPTION_INPUT = 'REELS_CAPTION_INPUT'
    CAPTION_ACTIONS = 'REELS_CAPTION_ACTIONS'
    
    # Функции
    ADD_FEATURES = 'REELS_ADD_FEATURES'
    ADD_CAPTION = 'REELS_ADD_CAPTION'
    ADD_HASHTAGS = 'REELS_ADD_HASHTAGS'
    ADD_USERTAGS = 'REELS_ADD_USERTAGS'
    ADD_LOCATION = 'REELS_ADD_LOCATION'
    ADD_MUSIC = 'REELS_ADD_MUSIC'
    CHOOSE_COVER = 'REELS_CHOOSE_COVER'
    UPLOAD_COVER = 'REELS_UPLOAD_COVER'
    TIME_COVER = 'REELS_TIME_COVER'
    BULK_USERTAGS = 'REELS_BULK_USERTAGS'
    
    # Подтверждение
    CONFIRM_PUBLISH = 'REELS_CONFIRM_PUBLISH'
    SCHEDULE_TIME = 'REELS_SCHEDULE_TIME'

# Состояния для IGTV
class IGTVStates:
    MEDIA_UPLOAD = 'IGTV_MEDIA_UPLOAD'
    ENTER_TITLE = 'IGTV_ENTER_TITLE'
    ENTER_DESCRIPTION = 'IGTV_ENTER_DESCRIPTION'
    CHOOSE_COVER = 'IGTV_CHOOSE_COVER'
    UPLOAD_COVER = 'IGTV_UPLOAD_COVER'
    CONFIRM_PUBLISH = 'IGTV_CONFIRM_PUBLISH'
    SCHEDULE_TIME = 'IGTV_SCHEDULE_TIME' 