# Состояния для ConversationHandler
# Используются в handlers.py

# Состояния для добавления аккаунта
WAITING_USERNAME = 1
WAITING_PASSWORD = 2
WAITING_ACCOUNT_INFO = 12
WAITING_ACCOUNTS_FILE = 13
WAITING_COOKIES_INFO = 14
WAITING_NEW_PASSWORD = 15

# Состояния для настройки профиля
WAITING_ACCOUNT_SELECTION = 3
WAITING_BIO_OR_AVATAR = 4

# Состояния для публикации
WAITING_TASK_TYPE = 5
WAITING_MEDIA = 6
WAITING_CAPTION = 7

# Состояния для отложенной публикации
WAITING_SCHEDULE_TIME = 8

# Состояния для добавления прокси
WAITING_PROXY_INFO = 9

# Добавьте новую константу
BULK_ADD_ACCOUNTS = 10

# Состояния для настройки профиля
PROFILE_MENU = 100
EDIT_PROFILE_NAME = 101
EDIT_USERNAME = 102
EDIT_BIO = 103
EDIT_LINKS = 104
UPLOAD_PROFILE_PHOTO = 105
UPLOAD_POST = 106
ENTER_POST_CAPTION = 107
CONFIRM_PIN_POST = 108
CONFIRM_DELETE_PROFILE_PHOTO = 109
CONFIRM_DELETE_POSTS = 110
CONFIRM_DELETE_BIO = 111

# Состояния для управления профилем
class ProfileStates:
    EDIT_NAME = 20
    EDIT_USERNAME = 21
    EDIT_BIO = 22
    EDIT_LINKS = 23
    ADD_PHOTO = 24
    ADD_POST = 25

# Состояния для управления фото профиля
WAITING_PROFILE_PHOTO = 11

# Состояния для Stories
STORY_ADD_FEATURES = 200
STORY_ADD_MENTIONS = 201
STORY_ADD_LINK = 202
STORY_ADD_LOCATION = 203
STORY_ADD_HASHTAGS = 204
STORY_ADD_TEXT = 205

# Состояния для Reels
REELS_UPLOAD_MEDIA = 300
REELS_ADD_FEATURES = 301
REELS_ADD_CAPTION = 302
REELS_ADD_HASHTAGS = 303
REELS_ADD_USERTAGS = 304
REELS_ADD_LOCATION = 305
REELS_ADD_MUSIC = 306
# REELS_CHOOSE_VISIBILITY = 307 - удалено
REELS_CHOOSE_COVER = 308
REELS_UPLOAD_COVER = 309
REELS_TIME_COVER = 310
REELS_BULK_USERTAGS = 311
REELS_CONFIRM_PUBLISH = 312